services:
  - type: web
    name: mike-backend
    env: docker
    region: ohio
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://mikeoss-canada-frontend.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

  - type: web
    name: mike-frontend
    env: node
    region: ohio
    plan: starter
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run start"
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://mike-backend.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY
        sync: false
